# Generated by Django 6.0.7 on 2026-07-21 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(error_messages={'unique': 'Ya existe una empresa registrada con este RUC.'}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe contener exactamente 13 dígitos.', regex='^\\d{13}$')], verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='nombre comercial')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El código de la sucursal debe contener exactamente 3 dígitos.', regex='^\\d{3}$')], verbose_name='código')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('es_matriz', models.BooleanField(default=False, verbose_name='es matriz')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ('nombre',),
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unica_sucursal_codigo_por_empresa'), models.UniqueConstraint(condition=models.Q(('es_matriz', True)), fields=('empresa',), name='unica_sucursal_matriz_por_empresa')],
            },
        ),
    ]
