# Generated by Django 6.0.7 on 2026-07-13 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre de usuario.'}, help_text='Requerido. Máximo 150 caracteres. Puede contener letras, números, puntos, guiones y guiones bajos.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario solo puede contener letras, números, puntos, guiones y guiones bajos.', regex='^[\\w.-]+$')], verbose_name='nombre de usuario'),
        ),
    ]
