# Generated by Django 6.0.7 on 2026-07-21 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_options_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('administrador', 'Administrador'), ('contador_externo', 'Contador externo'), ('empleado', 'Empleado'), ('consulta', 'Solo consulta')], default='empleado', max_length=20, verbose_name='rol')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('revocada', 'Revocada')], default='pendiente', max_length=12, verbose_name='estado')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de invitación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aceptación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='empresas.empresa', verbose_name='empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'ordering': ('empresa', 'usuario'),
            },
        ),
        migrations.CreateModel(
            name='MembresiaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es sucursal principal')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asignación')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_asignadas', to='cuentas.membresia', verbose_name='membresía')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_asignadas', to='empresas.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'sucursal de membresía',
                'verbose_name_plural': 'sucursales de membresías',
                'ordering': ('membresia', 'sucursal'),
            },
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa'), name='unica_membresia_usuario_empresa'),
        ),
        migrations.AddConstraint(
            model_name='membresiasucursal',
            constraint=models.UniqueConstraint(fields=('membresia', 'sucursal'), name='unica_sucursal_por_membresia'),
        ),
        migrations.AddConstraint(
            model_name='membresiasucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('membresia',), name='unica_sucursal_principal_por_membresia'),
        ),
    ]
