# Generated by Django 6.0.7 on 2026-07-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_membresia_membresiasucursal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membresiasucursal',
            name='unica_sucursal_por_membresia',
        ),
        migrations.RemoveConstraint(
            model_name='membresiasucursal',
            name='unica_sucursal_principal_por_membresia',
        ),
        migrations.DeleteModel(
            name='MembresiaSucursal',
        ),
    ]
