# Generated by Django 6.0.7 on 2026-07-24 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio mensual')),
                ('precio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio anual')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'ordering': ('orden', 'precio_mensual'),
            },
        ),
        migrations.CreateModel(
            name='PlanModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_planes', to='suscripciones.modulo', verbose_name='módulo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_asignados', to='suscripciones.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'módulo del plan',
                'verbose_name_plural': 'módulos de los planes',
                'ordering': ('plan', 'modulo'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='modulos',
            field=models.ManyToManyField(related_name='planes', through='suscripciones.PlanModulo', to='suscripciones.modulo', verbose_name='módulos'),
        ),
        migrations.AddConstraint(
            model_name='planmodulo',
            constraint=models.UniqueConstraint(fields=('plan', 'modulo'), name='unico_modulo_por_plan'),
        ),
    ]
