# Generated by Django 6.0.7 on 2026-07-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuarios', 'Usuarios'), ('sucursales', 'Sucursales'), ('documentos_mensuales', 'Documentos mensuales')], max_length=30, verbose_name='tipo de límite')),
                ('cantidad', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para indicar que no existe límite.', null=True, verbose_name='cantidad')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='suscripciones.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'límite del plan',
                'verbose_name_plural': 'límites de los planes',
                'ordering': ('plan', 'tipo'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'tipo'), name='unico_tipo_limite_por_plan')],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('prueba', 'Periodo de prueba'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='pendiente', max_length=12, verbose_name='estado')),
                ('ciclo_facturacion', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10, verbose_name='ciclo de facturación')),
                ('precio_contratado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio contratado')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('renovacion_automatica', models.BooleanField(default=True, verbose_name='renovación automática')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='empresas.empresa', verbose_name='empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ('-fecha_inicio', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_contratado__gte', 0)), name='suscripcion_precio_no_negativo'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='suscripcion_fechas_validas'), models.UniqueConstraint(condition=models.Q(('estado__in', ('pendiente', 'prueba', 'activa', 'suspendida'))), fields=('empresa',), name='unica_suscripcion_vigente_por_empresa')],
            },
        ),
    ]
