# Generated by Django 6.0.1 on 2026-04-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('razonsocial', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
